# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeostatisticsLab
                                 A QGIS plugin
 Geostatical tool library fo QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-27
        copyright            : (C) 2026 by DICAM-UNIBO
        email                : stefano.bondua@unibo.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeostatisticsLab class from file GeostatisticsLab.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geostatisticslab import GeostatisticsLab
    return GeostatisticsLab(iface)
